In [1]:
import pandas as pd

In [17]:
import datetime as dt

In [68]:
df_steam = pd.read_parquet('../CleanData/steam_games.parquet')
df_steam.head()

,id,app_name,title,price,developer,release_date,tag_1980s,tag_1990's,tag_2.5d,tag_2d,...,spec_single-player,spec_stats,spec_steam achievements,spec_steam cloud,spec_steam leaderboards,spec_steam trading cards,spec_steam turn notifications,spec_steam workshop,spec_steamvr collectibles,spec_valve anti-cheat enabled
0,761140,Lost Summoner Kitty,Lost Summoner Kitty,4.99,Kotoshiro,2018-01-04,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,643980,Ironbound,Ironbound,0.00,Secret Level SRL,2018-01-04,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,670290,Real Pool 3D - Poolians,Real Pool 3D - Poolians,0.00,Poolians.com,2017-07-24,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,767400,弹炸人2222,弹炸人2222,0.99,彼岸领域,2017-12-07,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,772540,Battle Royale Trainer,Battle Royale Trainer,3.99,Trickjump Games Ltd,2018-01-04,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [69]:
genres = list(df_steam.filter(like= 'genre_').columns)

In [70]:
columnas = ['id', 'release_date']
columnas.extend(genres)

In [71]:
df_steam = df_steam[columnas]

In [72]:
df_steam['Año'] = df_steam['release_date'].dt.year

In [73]:
df_steam.drop(columns='release_date', inplace=True)

In [74]:
df_steam.head()

,id,genre_1990's,genre_2d,genre_3d platformer,genre_accounting,genre_action,genre_action rpg,genre_adventure,genre_animation &amp; modeling,genre_anime,...,genre_tower defense,genre_twin stick shooter,genre_utilities,genre_video production,genre_violent,genre_visual novel,genre_war,genre_web publishing,genre_zombies,Año
0,761140,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2018
1,643980,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2018
2,670290,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2017
3,767400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2017
4,772540,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2018

In [75]:
df_user = pd.read_parquet('../CleanData/users_items.parquet', columns=['user_id', 'item_id', 'playtime_forever'])
df_user.head()

             user_id  item_id  playtime_forever
0  76561197970982479       10                 6
1  76561197970982479       20                 0
2  76561197970982479       30                 7
3  76561197970982479       40                 0
4  76561197970982479       50                 0

In [76]:
df = df_user.merge(df_steam, how= 'right', left_on= 'item_id', right_on= 'id').drop(columns=['item_id', 'id']).dropna()

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4159470 entries, 21 to 4179699
Columns: 124 entries, user_id to Año
dtypes: float64(1), int32(122), object(1)
memory usage: 2.0+ GB

In [78]:
df.head()

,user_id,playtime_forever,genre_1990's,genre_2d,genre_3d platformer,genre_accounting,genre_action,genre_action rpg,genre_adventure,genre_animation &amp; modeling,...,genre_tower defense,genre_twin stick shooter,genre_utilities,genre_video production,genre_violent,genre_visual novel,genre_war,genre_web publishing,genre_zombies,Año
21,UTNerd24,5.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1997
22,I_DID_911_JUST_SAYING,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1997
23,76561197962104795,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1997
24,r3ap3r78,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1997
25,saint556,13.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1997

In [79]:
df['playtime_forever'] = df['playtime_forever'] / 60

In [80]:
suma = df[genres].sum()
cols_cero = suma[suma == 0].index.tolist()

In [81]:
cols_cero

['genre_based on a novel',
 "genre_beat 'em up",
 'genre_bullet hell',
 'genre_chess',
 'genre_choose your own adventure',
 'genre_co-op',
 'genre_colorful',
 'genre_comic book',
 'genre_controller',
 'genre_dark comedy',
 'genre_dark humor',
 'genre_destruction',
 'genre_detective',
 'genre_documentary',
 'genre_episodic',
 'genre_exploration',
 'genre_fps',
 'genre_family friendly',
 'genre_fast-paced',
 'genre_first-person',
 'genre_game development',
 'genre_great soundtrack',
 'genre_hack and slash',
 'genre_hidden object',
 'genre_historical',
 'genre_horror',
 'genre_jrpg',
 'genre_local co-op',
 'genre_local multiplayer',
 'genre_medieval',
 'genre_memes',
 'genre_music',
 'genre_mystery',
 'genre_ninja',
 'genre_perma death',
 'genre_pixel graphics',
 'genre_point & click',
 'genre_remake',
 'genre_replay value',
 'genre_rogue-like',
 'genre_rogue-lite',
 "genre_shoot 'em up",
 'genre_shooter',
 'genre_soundtrack',
 'genre_stealth',
 'genre_time attack',
 'genre_time travel',
 'genre_top-down',
 'genre_top-down shooter',
 'genre_tower defense',
 'genre_twin stick shooter',
 'genre_violent',
 'genre_visual novel',
 'genre_war']

In [82]:
genres_filtered = [x for x in genres if x not in cols_cero]
genres_filtered

["genre_1990's",
 'genre_2d',
 'genre_3d platformer',
 'genre_accounting',
 'genre_action',
 'genre_action rpg',
 'genre_adventure',
 'genre_animation &amp; modeling',
 'genre_anime',
 'genre_arcade',
 'genre_atmospheric',
 'genre_audio production',
 'genre_casual',
 'genre_character customization',
 'genre_classic',
 'genre_comedy',
 'genre_cyberpunk',
 'genre_dark',
 'genre_dark fantasy',
 'genre_design & illustration',
 'genre_design &amp; illustration',
 'genre_difficult',
 'genre_early access',
 'genre_education',
 'genre_fantasy',
 'genre_female protagonist',
 'genre_free to play',
 'genre_funny',
 'genre_futuristic',
 'genre_gore',
 'genre_indie',
 'genre_isometric',
 'genre_lovecraftian',
 'genre_magic',
 'genre_massively multiplayer',
 'genre_metroidvania',
 'genre_moddable',
 'genre_multiplayer',
 'genre_open world',
 'genre_photo editing',
 'genre_platformer',
 'genre_puzzle',
 'genre_rpg',
 'genre_rpgmaker',
 'genre_rts',
 'genre_racing',
 'genre_real time tactics',
 'genre_real-time',
 'genre_retro',
 'genre_sandbox',
 'genre_sci-fi',
 'genre_side scroller',
 'genre_simulation',
 'genre_singleplayer',
 'genre_software training',
 'genre_sports',
 'genre_story rich',
 'genre_strategy',
 'genre_surreal',
 'genre_survival',
 'genre_survival horror',
 'genre_tactical',
 'genre_third person',
 'genre_utilities',
 'genre_video production',
 'genre_web publishing',
 'genre_zombies']

In [84]:
columnas = ['user_id', 'playtime_forever', 'Año']
columnas.extend(genres_filtered)
df = df[columnas]

In [86]:
# df.to_parquet('../CleanData/userforgenre.parquet')

In [93]:
def UserForGenre(genero: str):
    
    if not isinstance(genero, str):
        return {'Mensaje': 'El género ingresado debe ser una cadena de texto (string)'}
    
    genero = 'genre_' + genero
    genero = genero.lower()

    query_condition = genero + ' == 1'

    try:
        df = pd.read_parquet('../CleanData/userforgenre.parquet', columns=['user_id', 'Año', 'playtime_forever', genero]).query(query_condition).drop(columns=genero)
    except Exception:
        return {'Error': 'Género no encontrado. Ingrese un género válido'}

    df = df.groupby(['user_id', 'Año']).agg({'playtime_forever': 'sum'}).reset_index() 


    usuario_max_horas = df.nlargest(1, 'playtime_forever', 'all')['user_id'].values[0]
    df = df[df['user_id'] == usuario_max_horas]
    df.reset_index(inplace=True, drop=True)
    
    resultado = {
        f'Usuario con mas horas jugadas para el género {genero.replace("genre_", "")}:': usuario_max_horas,
        'Horas jugadas:': [{'Año:': int(df.loc[i,'Año']), 'Horas:': float(round(df.loc[i,'playtime_forever']/60, 2))} for i in range(len(df))]
    }

    return resultado

In [96]:
UserForGenre('asdegg')

{'Error': 'Género no encontrado. Ingrese un género válido'}